"""
generate_plots.py -- Report-quality plots for ML Assignment 1
Part 1 (var1): 5 plots  |  Part 2 (var2): 5 plots
Saved to: plots\\
"""
import sys, io, os, warnings
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from scipy import stats
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.linear_model import Lasso, Ridge
from sklearn.pipeline import Pipeline

# ──────────────────────────────────────────────────────────
# Paths
# ──────────────────────────────────────────────────────────
TRAIN_V1 = r"Data\BT2024208_train_var1.csv"
TRAIN_V2 = r"Data\BT2024208_train_var2.csv"
OUT      = r"plots"
os.makedirs(OUT, exist_ok=True)

# ──────────────────────────────────────────────────────────
# Global style
# ──────────────────────────────────────────────────────────
plt.rcParams.update({
    'font.family'      : 'DejaVu Sans',
    'font.size'        : 11,
    'axes.titlesize'   : 13,
    'axes.titleweight' : 'bold',
    'axes.labelsize'   : 12,
    'legend.fontsize'  : 8.5,
    'xtick.labelsize'  : 10,
    'ytick.labelsize'  : 10,
    'savefig.dpi'      : 300,
    'savefig.bbox'     : 'tight',
    'axes.grid'        : True,
    'grid.alpha'       : 0.3,
    'grid.linestyle'   : '--',
    'axes.spines.top'  : False,
    'axes.spines.right': False,
    'axes.facecolor'   : '#FAFAFA',
    'figure.facecolor' : 'white',
})

# ──────────────────────────────────────────────────────────
# Colour / style per model
# ──────────────────────────────────────────────────────────
MLABELS = [
    'OLS Linear',
    'Ridge(a=0.1)', 'Ridge(a=1.0)', 'Ridge(a=10)',
    'Lasso(a=0.001)', 'Lasso(a=0.01)', 'Lasso(a=0.1)',
    'EN(a=0.001)', 'EN(a=0.01,r=0.5)', 'EN(a=0.01,r=0.7)',
]
MCOLORS = [
    '#c0392b',
    '#5dade2', '#2e86c1', '#1a5276',
    '#f9e79f', '#f39c12', '#d35400',
    '#a9dfbf', '#27ae60', '#1e8449',
]
LW = [1.8, 1.4, 2.0, 1.4,  1.4, 2.0, 1.4,  1.4, 1.4, 1.4]
LS = ['-', '--', '-', ':',  '--', '-', ':',  '--', '-', ':']

# ──────────────────────────────────────────────────────────
# Load CV results from CSV files (generated by part1 and part2 scripts)
# ──────────────────────────────────────────────────────────
import pandas as pd

CSV1_PATH = r"Data\metrics_part1.csv"
CSV2_PATH = r"Data\metrics_part2.csv"

df1 = pd.read_csv(CSV1_PATH)
df2 = pd.read_csv(CSV2_PATH)

MODEL_NAME_MAP = {
    'Linear Regression': 'OLS Linear',
    'Ridge (alpha=0.1)': 'Ridge(a=0.1)',
    'Ridge (alpha=1.0)': 'Ridge(a=1.0)',
    'Ridge (alpha=10.0)': 'Ridge(a=10)',
    'Lasso (alpha=0.001)': 'Lasso(a=0.001)',
    'Lasso (alpha=0.01)': 'Lasso(a=0.01)',
    'Lasso (alpha=0.1)': 'Lasso(a=0.1)',
    'ElasticNet (a=0.001, l1=0.5)': 'EN(a=0.001)',
    'ElasticNet (a=0.01, l1=0.5)': 'EN(a=0.01,r=0.5)',
    'ElasticNet (a=0.01, l1=0.7)': 'EN(a=0.01,r=0.7)',
}
LABEL_TO_IDX = {label: idx for idx, label in enumerate(MLABELS)}

def build_matrices_from_csv(df, max_deg):
    mse_mat = np.zeros((max_deg, len(MLABELS)))
    r2_mat  = np.zeros((max_deg, len(MLABELS)))
    for _, row in df.iterrows():
        deg = int(row['degree'])
        raw_name = str(row['model_name'])
        label = MODEL_NAME_MAP.get(raw_name, raw_name)
        
        if 'model_index' in row and not pd.isna(row['model_index']):
            m_idx = int(row['model_index'])
        else:
            m_idx = LABEL_TO_IDX[label]
            
        mse_mat[deg - 1, m_idx] = float(row['cv_mse'])
        r2_mat[deg - 1, m_idx]  = float(row['cv_r2'])
    return mse_mat, r2_mat

P1_MSE, P1_R2 = build_matrices_from_csv(df1, 10)
P2_MSE, P2_R2 = build_matrices_from_csv(df2, 20)

D1 = np.arange(1, 11)
D2 = np.arange(1, 21)

# ──────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────
def legend_handles():
    return [Line2D([0], [0], color=MCOLORS[i], lw=LW[i],
                   linestyle=LS[i], label=MLABELS[i]) for i in range(10)]

def save(fig, name):
    path = os.path.join(OUT, name)
    fig.savefig(path, dpi=300, bbox_inches='tight')
    plt.close(fig)
    print('  Saved:', name)

def build_pipe(model, deg, X, y):
    pipe = Pipeline([
        ('poly',  PolynomialFeatures(degree=deg, include_bias=True)),
        ('scale', StandardScaler()),
        ('model', model),
    ])
    pipe.fit(X, y)
    return pipe

# ──────────────────────────────────────────────────────────
# Load data and fit final selected models
# ──────────────────────────────────────────────────────────
df1 = pd.read_csv(TRAIN_V1)
df2 = pd.read_csv(TRAIN_V2)
X1, y1 = df1[['x1','x2','x3','x4','x5','x6']].values, df1['y'].values
X2, y2 = df2[['x1','x2','x3']].values, df2['y'].values

# P1 final: Lasso(0.01), degree 5
pipe1 = build_pipe(Lasso(alpha=0.01, max_iter=10000, tol=0.01), 5, X1, y1)
yh1   = pipe1.predict(X1)
res1  = y1 - yh1

# P2 final: Ridge(1.0), degree 10
pipe2 = build_pipe(Ridge(alpha=1.0), 10, X2, y2)
yh2   = pipe2.predict(X2)
res2  = y2 - yh2

R2_p1 = 1 - np.var(res1) / np.var(y1)
R2_p2 = 1 - np.var(res2) / np.var(y2)
print(f'Final models fitted. P1 Train R2={R2_p1:.4f}  P2 Train R2={R2_p2:.4f}')

# ══════════════════════════════════════════════════════════
#  PART 1  —  5 PLOTS
# ══════════════════════════════════════════════════════════
print('\n--- PART 1 ---')

# P1-1  CV MSE vs Degree  (log scale)
fig, ax = plt.subplots(figsize=(10, 5.5))
for i in range(10):
    ax.semilogy(D1, P1_MSE[:, i], color=MCOLORS[i], lw=LW[i],
                linestyle=LS[i], marker='o', ms=4, label=MLABELS[i], alpha=0.9)
ax.scatter([5], [0.3606], s=220, zorder=9, color='#f39c12',
           edgecolors='black', linewidths=1.5, marker='*')
ax.annotate('Selected model\nLasso(a=0.01), deg=5\nCV MSE=0.3606',
            xy=(5, 0.3606), xytext=(7.2, 0.17), fontsize=9,
            arrowprops=dict(arrowstyle='->', color='#555'),
            bbox=dict(boxstyle='round,pad=0.3', fc='#fff3cd', ec='#f39c12', alpha=0.95))
ax.set_xlabel('Polynomial Degree')
ax.set_ylabel('CV MSE  (log scale)')
ax.set_title('Part 1 (var1) — CV MSE vs Degree: All Models')
ax.set_xticks(D1)
ax.legend(handles=legend_handles(), loc='upper right', ncol=2, framealpha=0.9)
ax.set_xlim(0.5, 10.5)
save(fig, 'p1_1_cv_mse_vs_degree.png')

# P1-2  CV R2 vs Degree
fig, ax = plt.subplots(figsize=(10, 5.5))
for i in range(10):
    ax.plot(D1, np.clip(P1_R2[:, i], -0.6, 1.0), color=MCOLORS[i], lw=LW[i],
            linestyle=LS[i], marker='o', ms=4, label=MLABELS[i], alpha=0.9)
ax.axhline(0, color='grey', lw=0.8, linestyle='--', label='R2 = 0')
ax.scatter([5], [0.9655], s=220, zorder=9, color='#f39c12',
           edgecolors='black', linewidths=1.5, marker='*')
ax.annotate('Selected: CV R2=0.9655\nLasso(a=0.01), deg=5',
            xy=(5, 0.9655), xytext=(7, 0.72), fontsize=9,
            arrowprops=dict(arrowstyle='->', color='#555'),
            bbox=dict(boxstyle='round,pad=0.3', fc='#fff3cd', ec='#f39c12', alpha=0.95))
ax.set_xlabel('Polynomial Degree')
ax.set_ylabel('CV R2  (clamped at -0.6)')
ax.set_title('Part 1 (var1) — CV R2 vs Degree: All Models')
ax.set_xticks(D1)
ax.legend(handles=legend_handles(), loc='lower right', ncol=2, framealpha=0.9)
ax.set_xlim(0.5, 10.5)
save(fig, 'p1_2_cv_r2_vs_degree.png')

# P1-3  Best CV MSE per Degree — bar chart
best_mse = P1_MSE.min(axis=1)
best_idx = P1_MSE.argmin(axis=1)
fig, ax = plt.subplots(figsize=(9, 5))
bars = ax.bar(D1, best_mse, color=[MCOLORS[i] for i in best_idx],
              edgecolor='white', linewidth=1.2, zorder=3)
for bar, val, mi in zip(bars, best_mse, best_idx):
    ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.012,
            f'{val:.3f}', ha='center', va='bottom', fontsize=8.5, fontweight='bold')
    short = MLABELS[mi].split('(')[0]
    ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() * 0.45,
            short, ha='center', va='center', fontsize=7,
            color='white', fontweight='bold')
ax.scatter([5], [best_mse[4]], s=240, zorder=10,
           color='gold', edgecolors='black', linewidths=1.5, marker='*')
ax.set_xlabel('Polynomial Degree')
ax.set_ylabel('Best CV MSE')
ax.set_title('Part 1 (var1) — Best CV MSE per Degree\n(bar colour = winning model family)')
ax.set_xticks(D1)
ax.set_ylim(0, max(best_mse) * 1.22)
# Legend patches
from matplotlib.patches import Patch
families = {'OLS': '#c0392b', 'Ridge': '#2e86c1', 'Lasso': '#f39c12', 'ElasticNet': '#27ae60'}
ax.legend([Patch(fc=c, label=n) for n, c in families.items()],
          families.keys(), loc='upper right', fontsize=9)
save(fig, 'p1_3_best_mse_per_degree.png')

# P1-4  Actual vs Predicted (training set)
fig, ax = plt.subplots(figsize=(6.5, 6.5))
sc = ax.scatter(y1, yh1, alpha=0.4, s=18, c=np.abs(res1), cmap='YlOrRd', edgecolors='none')
plt.colorbar(sc, ax=ax, label='|Residual|')
mn, mx = min(y1.min(), yh1.min()), max(y1.max(), yh1.max())
ax.plot([mn, mx], [mn, mx], 'k--', lw=1.5, label='Perfect fit')
ax.text(0.05, 0.93,
        f'Train R2  = {R2_p1:.4f}\nTrain MSE = {np.mean(res1**2):.4f}',
        transform=ax.transAxes, fontsize=10,
        bbox=dict(boxstyle='round', fc='white', ec='#ccc', alpha=0.92))
ax.set_xlabel('Actual y')
ax.set_ylabel('Predicted y')
ax.set_title('Part 1 (var1) — Actual vs Predicted\n(Lasso a=0.01, Degree 5, Training Set)')
ax.legend(fontsize=9)
ax.set_aspect('equal', 'box')
save(fig, 'p1_4_actual_vs_predicted.png')

# P1-5  Residuals Analysis (2-panel)
fig, axes = plt.subplots(1, 2, figsize=(12, 5))
# Left: residuals vs fitted
ax = axes[0]
ax.scatter(yh1, res1, alpha=0.35, s=18, color='#2e86c1', edgecolors='none')
ax.axhline(0, color='red', lw=1.5, linestyle='--')
ax.set_xlabel('Fitted Values')
ax.set_ylabel('Residuals')
ax.set_title('Residuals vs Fitted Values')
# Right: histogram + normal curve
ax = axes[1]
mu, sd = res1.mean(), res1.std()
ax.hist(res1, bins=40, density=True, color='#f39c12', alpha=0.7, edgecolor='white')
xc = np.linspace(res1.min(), res1.max(), 300)
ax.plot(xc, stats.norm.pdf(xc, mu, sd), 'r-', lw=2,
        label=f'Normal(mu={mu:.3f}, sd={sd:.3f})')
ax.set_xlabel('Residual Value')
ax.set_ylabel('Density')
ax.set_title('Residual Distribution')
ax.legend(fontsize=9)
fig.suptitle('Part 1 (var1) — Residuals Analysis  (Lasso a=0.01, Degree 5)',
             fontsize=12, fontweight='bold', y=1.02)
save(fig, 'p1_5_residuals_analysis.png')

# ══════════════════════════════════════════════════════════
#  PART 2  —  5 PLOTS
# ══════════════════════════════════════════════════════════
print('\n--- PART 2 ---')
REG = [1, 2, 3, 4, 5, 6, 7, 8, 9]   # regularised models only (skip OLS=0)

# P2-1  CV MSE vs Degree (regularised, log scale)
fig, ax = plt.subplots(figsize=(11, 5.5))
for i in REG:
    ax.semilogy(D2, P2_MSE[:, i], color=MCOLORS[i], lw=LW[i],
                linestyle=LS[i], marker='o', ms=3.5, label=MLABELS[i], alpha=0.9)
ax.scatter([11], [0.2647], s=220, zorder=9, color='#e74c3c',
           edgecolors='black', linewidths=1.5, marker='D')
ax.scatter([10], [0.2673], s=220, zorder=9, color='gold',
           edgecolors='black', linewidths=1.5, marker='*')
ax.annotate('Raw best (deg 11)\nCV MSE=0.2647',
            xy=(11, 0.2647), xytext=(14.5, 0.19), fontsize=8.5,
            arrowprops=dict(arrowstyle='->', color='#e74c3c'),
            bbox=dict(boxstyle='round,pad=0.3', fc='#fadbd8', ec='#e74c3c', alpha=0.95))
ax.annotate('Selected (deg 10)\nCV MSE=0.2673 (+1%)',
            xy=(10, 0.2673), xytext=(5.5, 0.19), fontsize=8.5,
            arrowprops=dict(arrowstyle='->', color='#f39c12'),
            bbox=dict(boxstyle='round,pad=0.3', fc='#fff3cd', ec='#f39c12', alpha=0.95))
ax.set_xlabel('Polynomial Degree')
ax.set_ylabel('CV MSE  (log scale)')
ax.set_title('Part 2 (var2) — CV MSE vs Degree: Regularised Models (degrees 1-20)')
ax.set_xticks(D2)
ax.tick_params(axis='x', rotation=45)
handles_reg = [Line2D([0],[0],color=MCOLORS[i],lw=LW[i],
               linestyle=LS[i],label=MLABELS[i]) for i in REG]
ax.legend(handles=handles_reg, loc='upper right', ncol=2, framealpha=0.9)
ax.set_xlim(0.5, 20.5)
save(fig, 'p2_1_cv_mse_vs_degree.png')

# P2-2  CV R2 vs Degree (regularised)
fig, ax = plt.subplots(figsize=(11, 5.5))
for i in REG:
    ax.plot(D2, np.clip(P2_R2[:, i], 0.88, 1.0), color=MCOLORS[i], lw=LW[i],
            linestyle=LS[i], marker='o', ms=3.5, label=MLABELS[i], alpha=0.9)
ax.scatter([11], [0.9937], s=220, zorder=9, color='#e74c3c',
           edgecolors='black', linewidths=1.5, marker='D', label='Raw best (deg 11)')
ax.scatter([10], [0.9936], s=220, zorder=9, color='gold',
           edgecolors='black', linewidths=1.5, marker='*', label='Selected (deg 10)')
ax.set_xlabel('Polynomial Degree')
ax.set_ylabel('CV R2  (clamped >= 0.88)')
ax.set_title('Part 2 (var2) — CV R2 vs Degree: Regularised Models (degrees 1-20)')
ax.set_xticks(D2)
ax.tick_params(axis='x', rotation=45)
ax.legend(handles=handles_reg, loc='lower right', ncol=2, framealpha=0.9)
ax.set_xlim(0.5, 20.5)
save(fig, 'p2_2_cv_r2_vs_degree.png')

# P2-3  Tolerance Selection — zoomed (Ridge family, degrees 6-15)
dz = np.arange(6, 16)
iz = dz - 1
RAW_BEST  = 0.2647
THRESHOLD = RAW_BEST * 1.01   # 0.2673

fig, ax = plt.subplots(figsize=(10, 5.5))
ax.plot(dz, P2_MSE[iz, 1], color=MCOLORS[1], lw=2.0, marker='o', ms=6, label='Ridge(a=0.1)')
ax.plot(dz, P2_MSE[iz, 2], color=MCOLORS[2], lw=2.5, marker='s', ms=6, label='Ridge(a=1.0)')
ax.plot(dz, P2_MSE[iz, 3], color=MCOLORS[3], lw=2.0, marker='^', ms=6, label='Ridge(a=10.0)')
ax.axhline(RAW_BEST,  color='#e74c3c', lw=1.8, linestyle='--',
           label=f'Raw best MSE = {RAW_BEST:.4f}')
ax.axhline(THRESHOLD, color='#f39c12', lw=1.8, linestyle='-.',
           label=f'1% threshold = {THRESHOLD:.4f}')
ax.axvspan(9.6, 11.4, alpha=0.07, color='#f5cba7')
ax.scatter([11], [0.2647], s=260, zorder=9, color='#e74c3c',
           edgecolors='black', linewidths=1.5, marker='D')
ax.scatter([10], [0.2673], s=260, zorder=9, color='gold',
           edgecolors='black', linewidths=1.5, marker='*')
ax.annotate('Raw best\ndeg=11, MSE=0.2647', xy=(11, 0.2647),
            xytext=(12.6, 0.256), fontsize=9,
            arrowprops=dict(arrowstyle='->', color='#e74c3c'))
ax.annotate('Selected (simpler)\ndeg=10, MSE=0.2673\nwithin 1% tolerance',
            xy=(10, 0.2673), xytext=(7.1, 0.280), fontsize=9,
            arrowprops=dict(arrowstyle='->', color='#f39c12'),
            bbox=dict(boxstyle='round,pad=0.3', fc='#fff3cd', ec='#f39c12', alpha=0.95))
ax.set_xlabel('Polynomial Degree')
ax.set_ylabel('CV MSE')
ax.set_title('Part 2 (var2) — Parsimony via 1% Tolerance Criterion\n(Ridge family, degrees 6-15)')
ax.set_xticks(dz)
ax.legend(loc='upper left', framealpha=0.9)
ax.set_ylim(0.240, 0.370)
save(fig, 'p2_3_tolerance_selection.png')

# P2-4  Actual vs Predicted (training set)
fig, ax = plt.subplots(figsize=(6.5, 6.5))
sc = ax.scatter(y2, yh2, alpha=0.4, s=18, c=np.abs(res2), cmap='YlOrRd', edgecolors='none')
plt.colorbar(sc, ax=ax, label='|Residual|')
mn, mx = min(y2.min(), yh2.min()), max(y2.max(), yh2.max())
ax.plot([mn, mx], [mn, mx], 'k--', lw=1.5, label='Perfect fit')
ax.text(0.05, 0.93,
        f'Train R2  = {R2_p2:.4f}\nTrain MSE = {np.mean(res2**2):.4f}',
        transform=ax.transAxes, fontsize=10,
        bbox=dict(boxstyle='round', fc='white', ec='#ccc', alpha=0.92))
ax.set_xlabel('Actual y')
ax.set_ylabel('Predicted y')
ax.set_title('Part 2 (var2) — Actual vs Predicted\n(Ridge a=1.0, Degree 10, Training Set)')
ax.legend(fontsize=9)
ax.set_aspect('equal', 'box')
save(fig, 'p2_4_actual_vs_predicted.png')

# P2-5  Residuals Analysis (2-panel)
fig, axes = plt.subplots(1, 2, figsize=(12, 5))
ax = axes[0]
ax.scatter(yh2, res2, alpha=0.35, s=18, color='#2e86c1', edgecolors='none')
ax.axhline(0, color='red', lw=1.5, linestyle='--')
ax.set_xlabel('Fitted Values')
ax.set_ylabel('Residuals')
ax.set_title('Residuals vs Fitted Values')
ax = axes[1]
mu2, sd2 = res2.mean(), res2.std()
ax.hist(res2, bins=40, density=True, color='#2e86c1', alpha=0.7, edgecolor='white')
xc2 = np.linspace(res2.min(), res2.max(), 300)
ax.plot(xc2, stats.norm.pdf(xc2, mu2, sd2), 'r-', lw=2,
        label=f'Normal(mu={mu2:.3f}, sd={sd2:.3f})')
ax.set_xlabel('Residual Value')
ax.set_ylabel('Density')
ax.set_title('Residual Distribution')
ax.legend(fontsize=9)
fig.suptitle('Part 2 (var2) — Residuals Analysis  (Ridge a=1.0, Degree 10)',
             fontsize=12, fontweight='bold', y=1.02)
save(fig, 'p2_5_residuals_analysis.png')

print(f'\nAll 10 plots saved to: {OUT}')